[package]
name = "galaxy_buds_rs"
version = "0.2.11"
authors = ["jojii <jojii@gmx.net>"]
edition = "2024"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/JojiiOfficial/GalaxyBuds-rs"
description = "The Galaxy Buds rfcomm protocol reverse engineered"

[dependencies]
async-std = "1.13"
bluetooth-serial-port-async = "0.6"
serde = { version = "1.0", features = ["derive"] }
